# Generated by Django 2.2.5 on 2020-11-11 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20200923_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='romm_type',
            new_name='room_type',
        ),
    ]
