# Generated by Django 2.2.5 on 2020-11-16 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20201111_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='isinstant_book',
            new_name='instant_book',
        ),
    ]
