# Generated by Django 2.2.5 on 2020-11-16 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20201116_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guest',
            new_name='guests',
        ),
    ]
