# Generated by Django 2.2.5 on 2020-09-22 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200601_1600'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeStampedModel',
        ),
    ]
